branches:
  only:
    - master

image:
- Visual Studio 2017

services:
  - iis
  - mssql2017

install:
  - ps: |
        function AddToPath([string] $path) {
  
          $key = "PATH"
          $currentPath = [Environment]::GetEnvironmentVariable($key, "Machine")

          if($currentPath.Contains($path)) {
            Write-Warning "'$path' already exists in $key, nothing added"
            return
          }  
  
          Write-Host "Adding '$path' to $key"
          if($path.EndsWith(";")) {
            $newPath = $currentPath + "$path;"
          }else {
            $newPath = $currentPath + ";$path;"
          }
          [Environment]::SetEnvironmentVariable($key, $newPath, "Machine")
        }
  - ps: choco install make
  - ps: AddToPath "C:\ProgramData\chocolatey\lib\make\tools\bin"
  
before_build:
  - cmd: make --version

build_script:
  - cmd: make build APPLICATION=iisconfig
  - cmd: make build APPLICATION=sqlserver

after_build:
  # using appveyor native ps for running tests, 32-bit make possibly runs 32-bit ps 
  # which fails to register cmdlets e.g. AppPool-Exists correctly
  - ps: iisconfig\tests\iisconfigtest.ps1 
  - cmd: make test-package APPLICATION=iisconfig BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER% GIT_COMMIT=%APPVEYOR_REPO_COMMIT% NUGET_SOURCE=%APPVEYOR_BUILD_FOLDER%
  - cmd: make test APPLICATION=sqlserver DBSERVER="(local)\SQL2017" TRUSTED_CONNECTION=false
  - cmd: make test-package APPLICATION=sqlserver BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER% GIT_COMMIT=%APPVEYOR_REPO_COMMIT% NUGET_SOURCE=%APPVEYOR_BUILD_FOLDER%
  
artifacts:
  - path: '**\*.nupkg' # push all *.nupkg files in build directory recursively